### PR TITLE
operator: Filter vault-operator cache to reduce memory usage

### LINKED ISSUE #1288: vault-operator pod stability when watching all namespaces
vault-operator unstable and fails with log messages attached to the case. I am using helm charts version 1.10.1 for deployment.

**Expected behaviour**:
I would expect it working.

**Steps to reproduce the bug**:
install it in with option to watch all namespaces.

**Additional context**:
When I run it with watching single namespace I don't have any problems.
What I noticed additionally memory usage goes really high. it starts with around 700MB and goes up to 6GB

**Environment details**:
- Kubernetes version (e.g. v1.10.2): v1.15.6
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): local k8s deployment
- bank-vaults version (e.g. 0.4.17): 1.10.1
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): attached
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: attached.
[helm-override.txt](https://github.com/banzaicloud/bank-vaults/files/6240043/helm-override.txt)

[vault-operator.txt](https://github.com/banzaicloud/bank-vaults/files/6240029/vault-operator.txt)

/kind bug

### PR DESCRIPTION
**Pull request by majimenez-stratio**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #1288 
| License         | Apache 2.0

### What's in this PR?
Upgrade controller-runtime to latest release (v0.11.2) and filter cache to only target those resources created by the controller/labeled with common keys. `app.kubernetes.io/name in (vault, vault-configurator)`

### Why?
In clusters with large number of configmaps, vault-operator memory usage is very high (~2Gi for 60k configmaps). While no cluster should have that many, I think we don't need to cache all of those.

### Additional context
In previous conditions, using v1.15.2, this is the memory usage ~1m after launch:

```
# k top pods -n keos-core vault-operator-86b8bf4596-gqpgr
NAME                              CPU(cores)   MEMORY(bytes)   
vault-operator-86b8bf4596-gqpgr   85m          2091Mi
```

This is the memory usage with the changes included in this PR in the same conditions:

```
# k top pods -n keos-core vault-operator-65d6c98759-wvbwp 
NAME                              CPU(cores)   MEMORY(bytes)   
vault-operator-65d6c98759-wvbwp   2m           33Mi
```

### Checklist
- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### To Do
- [ ] Check if all the kinds filtered actually have the right label
- [ ] Haven't thoroughly tested all features of vault CR

### CODE REVIEW

**Comment by bonifaido** [comment]
Don't worry we have a flaky test framework around the webhook, this works fine locally! (resources on GitHub is a bit little for the whole setup with Kubernetes).

**Comment by bonifaido** [comment]
I was checking the logs of the acceptance test and it looks like the vault-configurer pod can't start now for some reason, that is probably because of the changes (not the flaky part of the test).

**Comment by majimenez-stratio** [comment]
I think I can take a look at it. Any errors in the log?

**Comment by bonifaido** [comment]
Yes, it seems that there is no vault-config file available for the configurer (all in the build logs):
```
+ kubectl logs deployment/vault-configurer
Found 2 pods, using pod/vault-configurer-6f7fbd89b8-qk2fz
{"level":"info","msg":"vault metrics exporter enabled: :9091/metrics","time":"2022-05-13T18:51:27Z"}
{"level":"fatal","msg":"error reading vault config template: open vault-config.yml: no such file or directory","time":"2022-05-13T18:51:27Z"}
```

**Comment by ALX-TH** [comment]
hi @majimenez-stratio @bonifaido and thans for fix.
Is there any timeline hen we can expect this changes to be released ?
Thanks a lot!

**Comment by bonifaido** [comment]
@majimenez-stratio once you are there please rebase on the main branch.

**Comment by majimenez-stratio** [comment]
Sorry, didn't have the time to look at it. Hope I find some time during the week to fix the issues with vault-configurer. Sorry!

**Comment by majimenez-stratio** [comment]
Sorry @bonifaido, I rebased the PR but I can't find the error you mentioned. What I'm getting is this error instead:

```
+ kubectl logs -n vswh deployment/vault-secrets-webhook
Error from server (NotFound): namespaces "vswh" not found
Error: Process completed with exit code 1.
```
Any advice on how can I fix this one?

Moreover, I think vault-configurer is working as expected without any further change, according to the latest build logs:

```
2022-06-03T05:12:23.5994754Z + kubectl logs deployment/vault-configurer
2022-06-03T05:12:23.6783533Z {"level":"info","msg":"vault metrics exporter enabled: :9091/metrics","time":"2022-06-03T05:11:20Z"}
2022-06-03T05:12:23.6784616Z {"level":"info","msg":"applying config file : /config/vault-configurer/vault-config.yml","time":"2022-06-03T05:11:20Z"}
2022-06-03T05:12:23.6786025Z {"level":"info","msg":"checking if vault is sealed...","time":"2022-06-03T05:11:20Z"}
2022-06-03T05:12:23.6787135Z {"level":"info","msg":"watching directory for changes: /config/vault-configurer/","time":"2022-06-03T05:11:20Z"}
2022-06-03T05:12:23.6788223Z {"level":"error","msg":"error checking if vault is sealed: error checking status: Get \"https://vault.default:8200/v1/sys/seal-status\": dial tcp 10.96.98.124:8200: connect: connection refused, waiting 5s before trying again...","time":"2022-06-03T05:11:24Z"}
2022-06-03T05:12:23.6788988Z {"level":"info","msg":"checking if vault is sealed...","time":"2022-06-03T05:11:29Z"}
2022-06-03T05:12:23.6789960Z {"level":"error","msg":"error checking if vault is sealed: error checking status: Get \"https://vault.default:8200/v1/sys/seal-status\": dial tcp 10.96.98.124:8200: connect: connection refused, waiting 5s before trying again...","time":"2022-06-03T05:11:33Z"}
2022-06-03T05:12:23.6790710Z {"level":"info","msg":"checking if vault is sealed...","time":"2022-06-03T05:11:38Z"}
2022-06-03T05:12:23.6791233Z {"level":"info","msg":"vault is unsealed, configuring...","time":"2022-06-03T05:11:38Z"}
2022-06-03T05:12:23.6791798Z {"level":"info","msg":"adding auth method kubernetes (kubernetes)","time":"2022-06-03T05:11:38Z"}
2022-06-03T05:12:23.6792383Z {"level":"info","msg":"removing group-aliases ... map[string]string","time":"2022-06-03T05:11:38Z"}
2022-06-03T05:12:23.6792927Z {"level":"info","msg":"adding policy allow_secrets","time":"2022-06-03T05:11:38Z"}
2022-06-03T05:12:23.6793447Z {"level":"info","msg":"adding secret engine secret (kv)","time":"2022-06-03T05:11:38Z"}
2022-06-03T05:12:23.6793975Z {"level":"info","msg":"successfully configured vault","time":"2022-06-03T05:11:38Z"}
```

**Comment by ramizpolic** [comment]
@majimenez-stratio the project has been migrated to https://github.com/bank-vaults/vault-operator. 

In addition, we have also updated the controller-runtime to the latest version, so this might not be relevant anymore.
If you can test it out with the latest `vault-operator` version, we can decide if this needs to be reopened.

**Pull request closed without merging**
