### PR TITLE
feat: Add retry logic to vault secret engine mount process

### LINKED ISSUE #2449: we faced tuning and mounting error , google bucket rate limit
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/bank-vaults/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/bank-vaults/bank-vaults/issues/new/choose) without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Version

1.20.1

### Expected Behavior

Configurer works

### Actual Behavior

Configurer fails

### Steps To Reproduce

1. Use Google Bucket as the Vault backend.
2. Try to mount multiple Secrets engines(>10) 

### Logs

```shell
{"level":"error","msg":"error configuring vault: error configuring secret engines for vault: error adding secrets engines: error tuning llm_api in vault: Error making API request.\n\nURL: POST https://vault.vault:8200/v1/sys/mounts/mount_name/tune\nCode: 400. Errors:\n\n* 1 error occurred:\n\t* error closing connection: googleapi: Error 429: The object {bucketname}/core/mounts exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429., rateLimitExceeded\n\n","time":"2024-01-04T17:35:24Z"}
{"level":"info","msg":"Failed applying configuration file: /config/vault-configurer/vault-config.yml , sleeping for 1m0s before trying again","time":"2024-01-04T17:35:24Z"}
```
```


### Additional Information

I solved this problem with MR https://github.com/bank-vaults/bank-vaults/pull/2444/files , but I don't believe that it will be merged...

### PR DESCRIPTION
**Pull request by Reversaidx**
## Overview
After the vault update, we faced tuning and mounting error(after the upgrade to 14.4) due to Google storage  limit.

The code changes add an exponential backoff mechanism to the process of mounting a secret engine within the vault service. It enhances the system resiliency by reattempting to add or tune a secret engine into vault in case of failures within defined minimum and maximum time intervals. It finally exits after several unsuccessful attempts reaching the maximum backoff time.

Fixes #2449
```
{"level":"error","msg":"error configuring vault: error configuring secret engines for vault: error adding secrets engines: error tuning llm_api in vault: Error making API request.\n\nURL: POST https://vault.vault:8200/v1/sys/mounts/mount_name/tune\nCode: 400. Errors:\n\n* 1 error occurred:\n\t* error closing connection: googleapi: Error 429: The object {bucketname}/core/mounts exceeded the rate limit for object mutation operations (create, update, and delete). Please reduce your request rate. See https://cloud.google.com/storage/docs/gcs429., rateLimitExceeded\n\n","time":"2024-01-04T17:35:24Z"}
{"level":"info","msg":"Failed applying configuration file: /config/vault-configurer/vault-config.yml , sleeping for 1m0s before trying again","time":"2024-01-04T17:35:24Z"}
```

### CODE REVIEW

**Comment by akijakya** [comment]
Hi @Reversaidx, thanks for the contribution! Two quick remarks: please use the `log/slog` package instead of `logrus`, and sign the CLA! 🙂

**Comment by Reversaidx** [comment]
> Hi @Reversaidx, thanks for the contribution! Two quick remarks: please use the `log/slog` package instead of `logrus`, and sign the CLA! 🙂

Thx for the answer, fixed

**Review by akijakya — APPROVED** [review]
LGTM, @ramizpolic, @sagikazarmark WDYT?

**Review by ramizpolic — APPROVED** [review]
sorry for a delayed response, lgtm, thanks for contributing @Reversaidx!

**Pull request merged**
